# Generated by Django 3.1.2 on 2020-11-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shipping_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
    ]
